<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="swapnitapc" failures="0" tests="7" name="Testng.Verifyloginpagefb" time="23.877" errors="1" timestamp="2023-03-30T11:58:45 IST" skipped="2">
  <testcase classname="Testng.Verifyloginpagefb" name="openwebpage" time="0.000">
    <error message="Cannot invoke &quot;org.openqa.selenium.WebDriver.get(String)&quot; because &quot;this.driver&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebDriver.get(String)" because "this.driver" is null
at Testng.Verifyloginpagefb.openwebpage(Verifyloginpagefb.java:76)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- openwebpage -->
  <system-out/>
  <testcase classname="Testng.Verifyloginpagefb" name="verifyLoginPageFunction" time="0.000">
    <skipped/>
  </testcase> <!-- verifyLoginPageFunction -->
  <system-out/>
  <testcase classname="Testng.Verifyloginpagefb" name="verifyLoginPageFunction" time="15.157"/>
  <system-out/>
  <testcase classname="Testng.Verifyloginpagefb" name="verifyLoginPageFunction" time="8.714"/>
  <system-out/>
  <testcase classname="Testng.Verifyloginpagefb" name="verifyLoginPage" time="0.000">
    <skipped/>
  </testcase> <!-- verifyLoginPage -->
  <system-out/>
  <testcase classname="Testng.Verifyloginpagefb" name="verifyLoginPage" time="0.003"/>
  <system-out/>
  <testcase classname="Testng.Verifyloginpagefb" name="verifyLoginPage" time="0.003"/>
  <system-out/>
</testsuite> <!-- Testng.Verifyloginpagefb -->
